services:
  postgres:
    image: postgres:17-alpine
    container_name: elysia-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elysia_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  minio:
    image: quay.io/minio/minio:latest
    ports:
      - "10000:9000"
      - "10001:9001"
    command: ["server", "--console-address", ":9001", "/data"]
    volumes:
      - data-minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

  minio-buckets:
    image: quay.io/minio/mc:latest
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set dockerminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb dockerminio/assets;
      exit 0;
      "

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: elysia-app
  #   restart: unless-stopped
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     NODE_ENV: production
  #     HOST: 0.0.0.0
  #     PORT: 5000
  #     DATABASE_URL: postgresql://postgres:postgres@postgres:5432/elysia_db
  #     BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-your-random-secret-here}
  #     BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:5000}
  #     CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:5000,http://localhost:5173}
  #     LOG_LEVEL: ${LOG_LEVEL:-info}
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
volumes:
  postgres_data:
    driver: local
  data-minio:
