services:
  postgres:
    image: postgres:17-alpine
    container_name: elysia-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elysia_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  elysia-s3:
    image: docker.io/chrislusf/seaweedfs:3.65 # Pin ke versi 3.65 (atau cek tag terbaru di Docker Hub)
    container_name: elysia-s3
    command: "server -dir=/data -s3 -s3.config=/etc/seaweedfs/s3.json -s3.port=8333"
    ports:
      - "8333:8333"
    volumes:
      - seaweed-data:/data
      - ./s3.json:/etc/seaweedfs/s3.json:ro,Z
    restart: unless-stopped

  # 2. Service "Pekerja Sementara" untuk membuat bucket
  s3-init:
    image: amazon/aws-cli:latest
    container_name: s3-init
    depends_on:
      - elysia-s3
    environment:
      # Masukkan kredensial S3 kamu di sini
      - AWS_ACCESS_KEY_ID=${ACCESS_KEY:-admin}
      - AWS_SECRET_ACCESS_KEY=${SECRET_KEY:-admin123}
      - AWS_DEFAULT_REGION=us-east-1 # Wajib ada untuk S3, biarkan us-east-1
    entrypoint: >
      /bin/sh -c "
      echo 'Menunggu SeaweedFS S3 siap...';
      sleep 5;
      echo 'Mencoba membuat bucket...';
      aws s3 mb s3://assets --endpoint-url http://elysia-s3:8333 || true;
      echo 'Selesai!';
      exit 0;
      "

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: elysia-app
  #   restart: unless-stopped
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     NODE_ENV: production
  #     HOST: 0.0.0.0
  #     PORT: 5000
  #     DATABASE_URL: postgresql://postgres:postgres@postgres:5432/elysia_db
  #     BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-your-random-secret-here}
  #     BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:5000}
  #     CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:5000,http://localhost:5173}
  #     LOG_LEVEL: ${LOG_LEVEL:-info}
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
volumes:
  postgres_data:
    driver: local
  seaweed-data:
    driver: local
